name: Build

on: [push, pull_request]

jobs:

  build:
    name: Build for (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.6', '3.7', '3.8']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Python info
        shell: bash -l {0}
        run: |
          which python
          python --version
      - name: Install package and its dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Check style against standards using prospector
        shell: bash -l {0}
        run: prospector -o grouped -o pylint:pylint-report.txt
      - name: Build
        shell: bash -l {0}
        run: |
          pip install -e .[dev]
      - name: Check style against standards using prospector
        shell: bash -l {0}
        run: prospector -0 -o grouped -o pylint:pylint-report.txt
      - name: Test
        shell: bash -l {0}
        run: |
          pytest tests
          pytest --cov --cov-report term --cov-report xml --junitxml=xunit-result.xml
