on: [push]
name: Create issues for next steps
jobs:
  next_steps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Sonarcloud integration issue
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/next_steps/01_sonarcloud_integration.md
        id: sonarcloud
      - name: List created issues
        run: |
          echo 'Created issues that must be completed to have fully working Python package:'
          echo '* ${{ steps.sonarcloud.outputs.url }}'
          echo '* ${{ steps.sonarcloud.outputs.url }}'
          echo '* ${{ steps.sonarcloud.outputs.url }}'
          echo '* ${{ steps.sonarcloud.outputs.url }}'
          echo '* ${{ steps.sonarcloud.outputs.url }}'
          echo '* ${{ steps.sonarcloud.outputs.url }}'
      - name: Cleanup files needed to create next steps issues
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git rm .github/workflows/next_steps.yml
          git rm -r .github/next_steps
          git commit -am "Cleanup automated next step issue generator"
          git push
