on: [push]
name: Create issues for next steps
jobs:
  next_steps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/next_steps/01_sonarcloud_integration.md
        id: sonarcloud
      - run: 'echo Created issue number ${{ steps.sonarcloud.outputs.number }}'
      - run: 'echo Created ${{ steps.sonarcloud.outputs.url }}'
