name: quality
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo Hello
      - name: Detect fork
        uses: svrooij/secret-gate-action@v1
        with:
          inputsToCheck: 'SONAR_TOKEN'
          failOnMissing: 'true'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Sssh
        run: echo ${{ secrets.SONAR_TOKEN }}
