name: quality
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
env:
  SONAR_TOKEN_AVAILABLE: ${{ secrets.SONAR_TOKEN }}
jobs:
  sonarcloud:
    name: SonarCloud
    if: env.SONAR_TOKEN_AVAILABLE
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo Hello
      - name: Sssh
        run: echo ${{ secrets.SONAR_TOKEN }}
