name: quality
on:
  push:
  pull_request:
    types: [opened, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    env:
      SONAR_TOKEN_AVAILABLE: ${{ secrets.SONAR_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo Hello
      - name: Sssh
        if: ${{ env.SONAR_TOKEN_AVAILABLE }}
        run: echo ${{ secrets.SONAR_TOKEN }}
